-- Migration 066 : Extension des types de notification pour Epic 12

ALTER TABLE notification_queue
  DROP CONSTRAINT IF EXISTS notification_event_type_check;

ALTER TABLE notification_queue
  ADD CONSTRAINT notification_event_type_check
  CHECK (event_type IN (
    'RPPS_VERIFIE', 'RPPS_EN_ATTENTE',
    'ANNONCE_CREEE', 'ANNONCE_URGENTE', 'ANNONCE_POURVUE',
    'ANNONCE_NON_CONFIRMEE', 'ANNONCE_EXPIREE',
    'ANNONCE_FRAICHEUR_J7', 'ANNONCE_FRAICHEUR_J3',
    'AGGREGATION_ZERO_RESULTS', 'AGGREGATION_STRUCTURE_CHANGED', 'AGGREGATION_SOURCE_ERROR',
    'CANDIDATURE_RECUE', 'CANDIDATURE_ACCEPTEE', 'CANDIDATURE_REFUSEE',
    'CANDIDATURE_NON_RETENUE', 'RELANCE_CANDIDATURE_J2', 'RELANCE_CANDIDATURE_J5',
    'CANDIDATURE_RETIREE',
    'MESSAGE_RECU', 'SIGNALEMENT_MESSAGE',
    'CALENDRIER_OUTDATED', 'POST_REMPLACEMENT_NOTATION', 'NOTIFICATION_GROUPED',
    'CONTRAT_EN_ATTENTE', 'CONTRAT_CONFIRME',
    'PAIEMENT_INITIE', 'PAIEMENT_CONFIRME', 'PAIEMENT_ECHOUE',
    'LITIGE_OUVERT', 'LITIGE_RESOLU', 'LITIGE_ESCALADE',
    'EXPORT_DATA_READY', 'ACCOUNT_DELETION_SCHEDULED', 'DUPLICATE_RPPS_ALERT',
    'PROPOSITION_ENVOYEE', 'PROPOSITION_ACCEPTEE', 'PROPOSITION_DECLINEE', 'PARRAINAGE_ACTIF',
    -- Epic 12 — Administration
    'ALERTE_ADMIN_P1',
    'SIGNALEMENT_CREE',
    'SUPPORT_TICKET_CREE',
    -- Compatibilite ascendante
    'rpps_verified', 'new_annonce', 'candidature_accepted'
  ));
