// Types d'événements notification — registre centralisé (pas de string literals)
export const NOTIFICATION_TYPES = {
  // Epic 1
  RPPS_VERIFIE: 'RPPS_VERIFIE',
  RPPS_EN_ATTENTE: 'RPPS_EN_ATTENTE',
  // Epic 2
  ANNONCE_CREEE: 'ANNONCE_CREEE',
  ANNONCE_URGENTE: 'ANNONCE_URGENTE',
  ANNONCE_POURVUE: 'ANNONCE_POURVUE',
  ANNONCE_NON_CONFIRMEE: 'ANNONCE_NON_CONFIRMEE',
  ANNONCE_EXPIREE: 'ANNONCE_EXPIREE',
  ANNONCE_FRAICHEUR_J7: 'ANNONCE_FRAICHEUR_J7',
  ANNONCE_FRAICHEUR_J3: 'ANNONCE_FRAICHEUR_J3',
  // Epic 3
  AGGREGATION_ZERO_RESULTS: 'AGGREGATION_ZERO_RESULTS',
  AGGREGATION_STRUCTURE_CHANGED: 'AGGREGATION_STRUCTURE_CHANGED',
  AGGREGATION_SOURCE_ERROR: 'AGGREGATION_SOURCE_ERROR',
  // Epic 5
  CANDIDATURE_RECUE: 'CANDIDATURE_RECUE',
  CANDIDATURE_ACCEPTEE: 'CANDIDATURE_ACCEPTEE',
  CANDIDATURE_REFUSEE: 'CANDIDATURE_REFUSEE',
  CANDIDATURE_NON_RETENUE: 'CANDIDATURE_NON_RETENUE',
  CANDIDATURE_RETIREE: 'CANDIDATURE_RETIREE',
  RELANCE_CANDIDATURE_J2: 'RELANCE_CANDIDATURE_J2',
  RELANCE_CANDIDATURE_J5: 'RELANCE_CANDIDATURE_J5',
  // Epic 6
  MESSAGE_RECU: 'MESSAGE_RECU',
  SIGNALEMENT_MESSAGE: 'SIGNALEMENT_MESSAGE',
  // Epic 7
  CALENDRIER_OUTDATED: 'CALENDRIER_OUTDATED',
  POST_REMPLACEMENT_NOTATION: 'POST_REMPLACEMENT_NOTATION',
  NOTIFICATION_GROUPED: 'NOTIFICATION_GROUPED',
  // Epic 8
  CONTRAT_EN_ATTENTE: 'CONTRAT_EN_ATTENTE',
  CONTRAT_CONFIRME: 'CONTRAT_CONFIRME',
  // Epic 9 — Paiement Securise
  PAIEMENT_INITIE: 'PAIEMENT_INITIE',
  PAIEMENT_CONFIRME: 'PAIEMENT_CONFIRME',
  PAIEMENT_ECHOUE: 'PAIEMENT_ECHOUE',
  LITIGE_OUVERT: 'LITIGE_OUVERT',
  LITIGE_RESOLU: 'LITIGE_RESOLU',
  LITIGE_ESCALADE: 'LITIGE_ESCALADE',
  // Epic 10 — RGPD & Securite
  EXPORT_DATA_READY: 'EXPORT_DATA_READY',
  ACCOUNT_DELETION_SCHEDULED: 'ACCOUNT_DELETION_SCHEDULED',
  DUPLICATE_RPPS_ALERT: 'DUPLICATE_RPPS_ALERT',
  // Epic 11 — Reputation & Propositions
  PROPOSITION_ENVOYEE: 'PROPOSITION_ENVOYEE',
  PROPOSITION_ACCEPTEE: 'PROPOSITION_ACCEPTEE',
  PROPOSITION_DECLINEE: 'PROPOSITION_DECLINEE',
  PARRAINAGE_ACTIF: 'PARRAINAGE_ACTIF',
  // Epic 12 — Administration
  ALERTE_ADMIN_P1: 'ALERTE_ADMIN_P1',
  SIGNALEMENT_CREE: 'SIGNALEMENT_CREE',
  SUPPORT_TICKET_CREE: 'SUPPORT_TICKET_CREE',
} as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES];
